name: CD - Deploy to EC2
on:
  workflow_run:
    workflows: [ "Build and Push Docker Image" ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Trust EC2 host
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Login Docker Hub on EC2
        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Pull & restart
        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd ~/app && docker compose pull && docker compose up -d --remove-orphans && docker ps"
